Exercise 1: (Score : 1) Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [15]:
import numpy as np
arr1=np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
arr1=np.arange(1,11)
matrix=arr1.reshape(2,5)
print("2x5 matrix :",matrix)

2x5 matrix : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Exercise 2: (Score : 1) Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index

In [18]:
arr2=np.arange(1,21)
print(arr2)
Extracted_elements=arr2[5:15] 
print("Extracted_elements:",Extracted_elements)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Extracted_elements: [ 6  7  8  9 10 11 12 13 14 15]


Exercise 3: (Score : 2) Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4

In [20]:
import pandas as pd

# Create a Pandas series
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

# Add a new item 'pears' with value 4
fruit_series['pears'] = 4
print(fruit_series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


Exercise 4: (Score : 2)
Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [22]:
# Create a dataframe with columns: name, age, and gender
data = {
    'name': ['John', 'Anna', 'Peter', 'Linda', 'James', 'Maria', 'David', 'Sophia', 'William', 'Charlotte'],
    'age': [28, 22, 34, 29, 40, 35, 45, 32, 23, 27],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female']
}

df = pd.DataFrame(data)
print(df)


        name  age  gender
0       John   28    Male
1       Anna   22  Female
2      Peter   34    Male
3      Linda   29  Female
4      James   40    Male
5      Maria   35  Female
6      David   45    Male
7     Sophia   32  Female
8    William   23    Male
9  Charlotte   27  Female


Exercise 5: (Score : 1)
Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.


In [24]:
# Add a new column 'occupation'
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print(df)


        name  age  gender  occupation
0       John   28    Male  Programmer
1       Anna   22  Female     Manager
2      Peter   34    Male     Analyst
3      Linda   29  Female  Programmer
4      James   40    Male     Manager
5      Maria   35  Female     Analyst
6      David   45    Male  Programmer
7     Sophia   32  Female     Manager
8    William   23    Male     Analyst
9  Charlotte   27  Female  Programmer


Exercise 6: (Score : 1)
Select the rows of the dataframe where the age is greater than or equal to 30.


In [26]:
# Select rows where age is greater than or equal to 30
age_filtered_df = df[df['age'] >= 30]
print(age_filtered_df)


     name  age  gender  occupation
2   Peter   34    Male     Analyst
4   James   40    Male     Manager
5   Maria   35  Female     Analyst
6   David   45    Male  Programmer
7  Sophia   32  Female     Manager


Exercise 7: (Score : 2)
Convert this dataframe to a csv file and read that csv file, finally display the contents.



In [28]:
# Convert the dataframe to a CSV file
df.to_csv('people_data.csv', index=False)

# Read the CSV file
df_from_csv = pd.read_csv('people_data.csv')

# Display the contents
print(df_from_csv)


        name  age  gender  occupation
0       John   28    Male  Programmer
1       Anna   22  Female     Manager
2      Peter   34    Male     Analyst
3      Linda   29  Female  Programmer
4      James   40    Male     Manager
5      Maria   35  Female     Analyst
6      David   45    Male  Programmer
7     Sophia   32  Female     Manager
8    William   23    Male     Analyst
9  Charlotte   27  Female  Programmer
